name: 每日新闻推送

on:
  schedule:
    # 每天早上 8:00 (UTC 0:00, 北京时间 8:00)
    - cron: '0 0 * * *'
    # 每天晚上 8:00 (UTC 12:00, 北京时间 8:00)
    - cron: '0 12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  push-news:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行新闻推送
      env:
        PUSH_TYPE: ${{ secrets.PUSH_TYPE }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        CITY: ${{ secrets.CITY }}
      run: |
        python news_fetcher.py
